<?php

/**
 * @file
 * Contains rootstack_crappy_nodes.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rootstack_crappy_nodes_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rootstack_crappy_nodes module.
    case 'help.page.rootstack_crappy_nodes':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Test suscription to an event') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function rootstack_crappy_nodes_theme() {
  $theme = [];

  return $theme;
}
