<?php

/**
 * @file
 * Contains rootstack_sandbox.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_theme().
 */
function rootstack_sandbox_theme() {
  return [
    'fancy_nodes' => [
      'variables' => [
        'summary' => '',
        'some_nodes' => '',
        'other_nodes' => '',
        'total' => ''
      ],
    ]
  ];
}

function rootstack_sandbox_preprocess_fancy_nodes(&$vars) {
  dpm($vars);
  $block = \Drupal\block\Entity\Block::load('views_block__sdf_block_1');
  $em = \Drupal::entityManager();
  $test = $em->getViewBuilder('block')->view($block);
  $vars['summary'] = $test;
}